version: "2.1"

services:
  app:
    image: signalr
    restart: always
    networks:
      - web
      - default
    expose:
      - "80"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:signalr.xn--nrd-yla.no"
      - "traefik.port=80"
      - "traefik.protocol=http"
    build:
      context: .
      
networks:
  web:
    external: true
